# Generated by Django 2.1 on 2018-08-31 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180831_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='birth date'),
        ),
    ]
