# Generated by Django 2.1 on 2018-08-31 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postresponse',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.PostDetail'),
        ),
    ]
