# Generated by Django 2.0.4 on 2018-09-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180831_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postresponse',
            name='attending_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe'), ('', '')], default='', max_length=10, verbose_name='will you be attending?'),
        ),
    ]
