# Generated by Django 2.0.4 on 2018-09-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20180919_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetail',
            name='deactivate_post',
        ),
        migrations.AddField(
            model_name='postdetail',
            name='remove_post',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='False', max_length=50, verbose_name='remove listing'),
        ),
    ]
