# Generated by Django 2.0.4 on 2018-09-21 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20180920_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdetail',
            old_name='post_start_date',
            new_name='class_start_date',
        ),
        migrations.RenameField(
            model_name='postdetail',
            old_name='poster',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='postdetail',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='postdetail',
            name='post_end_date',
        ),
        migrations.AddField(
            model_name='postdetail',
            name='class_start_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='time'),
        ),
    ]
